Repository crossbario/crossbar, pull requests merged in 2022-03, with the labels that each got.

#1968 Fix proxy controller has_realm() logic
  crossbar/worker/proxy.py
Labels: bug, core

#1925 Parse cookie manualy if there is JSON in request header
  crossbar/router/cookiestore.py
Labels: CAA Signed

#1972 Fix proxy routes when multiple roles configured
  crossbar/worker/proxy.py
Labels: enhancement, core, needs-discussion
